#!/bin/sh
set -e

TF=$1
# Load natural timeframes
mysqlimport --ignore --local --fields-terminated-by=	 --lines-terminated-by='\r\n' -s -ufx fx *_$TF
rm -Rf *_$TF

# Create synthetic pairs
~/fx/synthetics.pl --timeframe=$TF

# Create synthetic timeframes
~/fx/updateTf.pl --start="4 days ago at midnight"
./TruncateWeekly.pl | mysql -u root fx
~/fx/updateTf.pl --timeframes=604800 --available-timeframe=day

# Dump downloadable rates
./dumpFiles.pl --timeframes=3600,86400

