#!/bin/sh
set -e

TF=$1
# Load natural timeframes
mysqlimport --ignore --local --fields-terminated-by='\t' --lines-terminated-by='\r\n' -s -ufxhistor -pfxhistor fx *_$TF
rm -Rf *_$TF

# Create synthetic pairs
synthetics.pl --timeframe=$TF

# Create synthetic timeframes
updateTf.pl --start="4 days ago at midnight" --available-timeframe=min
./TruncateWeekly.pl | mysql -ufx fx
updateTf.pl --timeframes=604800 --available-timeframe=day

# Dump downloadable rates
./dumpFiles.pl --timeframes=3600,86400

