#!/bin/sh
set -e

TF=$1
# Load natural timeframes
mysqlimport --local --fields-terminated-by=	 --lines-terminated-by='\r\n' -s -u root fxcm *.$TF
rm -Rf *.$TF

# Create synthetic pairs
~/fx/synthetics.pl --timeframe=$TF

# Create synthetic timeframes
~/fx/updateTf.pl --start="4 days ago at midnight"
./TruncateWeekly.pl | mysql -u root fxcm
~/fx/updateTf.pl --timeframe=604800 --available-timeframe=day
