#!/bin/sh
set -e

TF=$1
# Load natural timeframes
mysqlimport --ignore --local --fields-terminated-by=	 --lines-terminated-by='\r\n' -s -ufxcm fxcm *_$TF
rm -Rf *_$TF

# Create synthetic pairs
~/fx/synthetics.pl --timeframe=$TF

if [[ "$TF" == "7200" ]]; then
# Create synthetic timeframes
~/fx/updateTf.pl --start="5 days ago" --timeframes=7200 --available-timeframe=hour
~/fx/updateTf.pl --start="5 days ago" --timeframes=10800 --available-timeframe=hour
~/fx/updateTf.pl --start="5 days ago" --timeframes=14400 --available-timeframe=2hour
fi
