#!/bin/sh
set -e

#RatePrinter will write data in the $1 timeframe to individual files
#The other two arguments are the login details to the API account
wine ./RatePrinter.exe FX1125841001 3151 $TF 2> /dev/null
