#!/bin/sh

. ../config_real.sh
echo `date`     START
wine ./FXCMHistoryUpdater.exe $FXCM_USER $FXCM_PASSWORD $FXCM_TYPE `./dates.pl` # &> /dev/null < /dev/null
echo `date`     LOAD 5min
../Datafeed/load 300 . 0001-01-01
echo `date`     LOAD hour
../Datafeed/load 3600 . 0001-01-01
echo `date`     DONE
