#!/bin/sh

RUNDIR=$TRADER_HOME/data/fxcm/servers/Trader
CONFIG_FILE=$1

. $CONFIG_FILE

cd $RUNDIR
./Trader.pl --verbose --username=$FXCM_USER --password=$FXCM_PASSWORD --accountType=$FXCM_TYPE  >> trader_$FXCM_TYPE.log 2>&1 < /dev/null &
