#!/bin/sh

RUNDIR=$TRADER_HOME/data/fxcm/servers/Trader
CONFIG_FILE=$1

. $CONFIG_FILE

cd $RUNDIR
./Trader.pl --verbose --address=$SERVER_ADDRESS --port=$SERVER_PORT  >> trader_$FXCM_TYPE.log 2>&1 < /dev/null &
