#!/bin/sh

set -e

while getopts ":p" opt; do
    case $opt in
      c)
         USE_PROFILER=1
         ;;
    esac
done

HOMEDIR=~/Finance--HostedTrader

START_DATE="2010-08-18 06:00:00"
END_DATE="2011-10-26 04:00:00"

TZ=GMT
if [ $USE_PROFILER ]; then
    ARGS="-d:NYTProf"
#    ARGS="-MDevel::Cover"
fi

nice -n 19 perl $ARGS $HOMEDIR/data/fxcm/servers/Trader/Trader.pl --class=UnitTest --verbose --startDate="$START_DATE" --endDate="$END_DATE"
