#!/bin/sh

BASEDIR=~/fx/data/fxcm/servers
RUNDIR=$BASEDIR/Server

. $BASEDIR/config.sh

wine $RUNDIR/Server.exe 127.0.0.1 1500 $FXCM_USER $FXCM_PASSWORD $FXCM_TYPE >> $RUNDIR/server.log 2>&1 < /dev/null &
