#!/bin/sh
set -e

TF=$1
# Load natural timeframes
DATADIR=/dev/shm
mysqlimport --ignore --local --fields-terminated-by='\t' --lines-terminated-by='\n' -s -ufxcm fxcm $DATADIR/*_$TF 2> /tmp/mysqlimport.errors
rm -Rf $DATADIR/*_$TF

# Create synthetic pairs
~/fx/synthetics.pl --timeframe=$TF

# Create synthetic timeframes
if [[ "$TF" == "300" ]]; then
~/fx/updateTf.pl --start="15 days ago" --timeframes=900 --available-timeframe=5min --symbols=all
~/fx/updateTf.pl --start="15 days ago" --timeframes=1800 --available-timeframe=15min --symbols=all
fi

if [[ "$TF" == "3600" ]]; then
~/fx/updateTf.pl --start="15 days ago" --timeframes=7200 --available-timeframe=hour --symbols=all
~/fx/updateTf.pl --start="15 days ago" --timeframes=10800 --available-timeframe=hour --symbols=all
~/fx/updateTf.pl --start="15 days ago" --timeframes=14400 --available-timeframe=2hour --symbols=all
fi
